name: Build Cydia Repository

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Install dpkg-sig / utilities
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev bzip2 zstd

      - name: Generate Packages and Metadata
        run: |
          dpkg-scanpackages -m ./debs > ./Packages
          bzip2 -k -f ./Packages
          gzip -k -f ./Packages
          zstd -k -f ./Packages -o ./Packages.zst

      - name: Generate Packages and Metadata
        run: |
          dpkg-scanpackages -m ./debs /dev/null > ./Packages
          # Automatically normalize firmware dependencies for all packages to iOS 5.0 - 10.0
          sed -i 's/Depends: \(.*\), firmware (>= [0-9.]*)/Depends: \1, firmware (>= 5.0), firmware (<< 10.0)/g' ./Packages
          sed -i '/^Depends:.*firmware/! s/Depends: \(.*\)/Depends: \1, firmware (>= 5.0), firmware (<< 10.0)/g' ./Packages
          bzip2 -k -f ./Packages
          gzip -k -f ./Packages
          zstd -k -f ./Packages -o ./Packages.zst
